-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 20:27:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafe` DEFAULT CHARACTER SET utf8 ;
USE `cafe` ;

-- -----------------------------------------------------
-- Table `cafe`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe`.`productos` (
  `idproductos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `img` VARCHAR(200) NULL,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe`.`entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe`.`entradas` (
  `identradas` INT NOT NULL,
  `fecha` DATE NULL,
  `nit` VARCHAR(11) NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`identradas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe`.`salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe`.`salidas` (
  `idsalidas` INT NOT NULL,
  `fecha` DATE NULL,
  `nit` VARCHAR(11) NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`idsalidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe`.`detalleEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe`.`detalleEntrada` (
  `iddetalleEntrada` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(8,2) NULL,
  `idproductos` INT NOT NULL,
  `identradas` INT NOT NULL,
  PRIMARY KEY (`iddetalleEntrada`),
  CONSTRAINT `fk_detalleEntrada_productos`
    FOREIGN KEY (`idproductos`)
    REFERENCES `cafe`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleEntrada_entradas1`
    FOREIGN KEY (`identradas`)
    REFERENCES `cafe`.`entradas` (`identradas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalleEntrada_productos_idx` ON `cafe`.`detalleEntrada` (`idproductos`);

CREATE INDEX `fk_detalleEntrada_entradas1_idx` ON `cafe`.`detalleEntrada` (`identradas`);


-- -----------------------------------------------------
-- Table `cafe`.`detalleSalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe`.`detalleSalida` (
  `iddetalleSalida` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(8,2) NULL,
  `idproductos` INT NOT NULL,
  `idsalidas` INT NOT NULL,
  PRIMARY KEY (`iddetalleSalida`),
  CONSTRAINT `fk_detalleSalida_productos1`
    FOREIGN KEY (`idproductos`)
    REFERENCES `cafe`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleSalida_salidas1`
    FOREIGN KEY (`idsalidas`)
    REFERENCES `cafe`.`salidas` (`idsalidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalleSalida_productos1_idx` ON `cafe`.`detalleSalida` (`idproductos` ASC) VISIBLE;

CREATE INDEX `fk_detalleSalida_salidas1_idx` ON `cafe`.`detalleSalida` (`idsalidas` ASC) VISIBLE;
